### ISSUE TITLE
Add an additional release binary labeled, leo.zip for one M1 machines

### ISSUE THREAD

**Issue by aharshbe** [AleoHQ/welcome#257]
# Add an additional release binary labeled leo.zip

## Description
To remove the need to constantly update download links in developer docs and other locations, add an additional binary to [GitHub releases](https://github.com/AleoHQ/leo/releases) called `leo.zip`.

## Task
- [x] Cut an additional release now and in the future called `leo.zip`
- [x] Update the developer docs, [here](https://github.com/AleoHQ/leo/releases), to the formatted URL for downloading the latest version of leo, `https://github.com/AleoHQ/leo/latest/leo.zip`
  - [x] Remove the tab for each download in favor of a single download button. Leave the `Browse all Leo releases here.`
- [x] welcome PR
- [x] aleo-docs PR

**Comment by aharshbe** [comment]
- [./welcome PR](https://github.com/AleoHQ/welcome/pull/258)
